### PR TITLE
Day 11 & 12, hbldh

### PR DESCRIPTION
**Pull request by hbldh**

### CODE REVIEW

**Comment by magthe** [comment]
Just being curious here, how long does it take to get the solution to part 2 of the December 11 problem?

Part 1 took about a minute with your solution, and I've been waiting 11 minutes for part 2 now :)

**Comment by hbldh** [comment]
Abort half an hour. I am thinking about profiling it tonight and try to improve it...

**Comment by magthe** [comment]
It finished in about 1h on my machine here. I'm also struggling with speed of my solution, so I'm looking around for inspiration :)

**Comment by hbldh** [comment]
Mm, it is way too slow to do it the way it is now. Most time is spent in string comparisons and copying lists. I should find a some method with integer representations of chips and generators to speed it up.

**Comment by hbldh** [comment]
After some minor optimizations:
```
[Part 1] Minimum number of steps: XX (Runtime: 14.57 s)
[Part 2] Minimum number of steps: XX (Runtime: 1016.37 s)
```

**Comment by bjoreman** [comment]
Looking forward to getting to these problems myself. Perhaps I won't once I get there, but right now it sounds like fun trying to get all that faster :-) …

**Comment by magthe** [comment]
I've now managed to get mine down considerably, about 1min 40s on my system here. Needs a bit of cleanup before merging though. I also have another tweak I'd like to try out, if I have time.

**Comment by hbldh** [comment]
From Day 9 and forward they increased in difficulty somewhat IMO, with Day 11 as the most challenging one up until now.

**Pull request merged**
